import type { DragonElement } from "./dragon-summon";
import type { SynthParams } from "./types";

export const KINDS: DragonElement[] = ["EARTH", "WATER", "FIRE", "WIND"];

export const KIND_VOICE: Record<DragonElement, Partial<SynthParams>> = {
  EARTH: {
    waveform: "triangle",
    filterType: "lowpass",
    cutoff: 1180,
    resonance: 0.85,
    octave: -1,
    attack: 0.07,
    decay: 0.38,
    sustain: 0.9,
    release: 0.85,
    halloween: 0,
    waters: 0.08,
    unison: 2,
    volume: 0.84,
  },
  WATER: {
    waveform: "sine",
    filterType: "lowpass",
    cutoff: 2680,
    resonance: 0.52,
    octave: 0,
    attack: 0.12,
    decay: 0.42,
    sustain: 0.9,
    release: 0.96,
    halloween: 0,
    waters: 0.5,
    aether: 0.07,
    unison: 2,
    volume: 0.84,
  },
  FIRE: {
    waveform: "sawtooth",
    filterType: "lowpass",
    cutoff: 3800,
    resonance: 2.8,
    octave: 0,
    attack: 0.002,
    decay: 0.18,
    sustain: 0.62,
    release: 0.16,
    halloween: 0.28,
    waters: 0,
    unison: 1,
    volume: 0.84,
  },
  WIND: {
    waveform: "triangle",
    filterType: "highpass",
    cutoff: 320,
    resonance: 0.9,
    octave: 0,
    attack: 0.03,
    decay: 0.22,
    sustain: 0.72,
    release: 0.4,
    halloween: 0,
    waters: 0.06,
    aether: 0.22,
    unison: 3,
    volume: 0.84,
  },
};
