import { DEFAULT_PARAMS, type SynthParams } from "./types";

export type Preset = {
  id: string;
  name: string;
  params: SynthParams;
};

function voice(id: string, name: string, patch: Partial<SynthParams>): Preset {
  return { id, name, params: { ...DEFAULT_PARAMS, ...patch } };
}

export const PRESETS: Preset[] = [
  voice("init", "Forge Init", {}),
  voice("iron-horizon", "Iron Horizon", {
    waveform: "sawtooth",
    cutoff: 720,
    resonance: 3.4,
    attack: 0.04,
    decay: 0.55,
    sustain: 0.7,
    release: 0.9,
    unison: 3,
    halloween: 0.18,
    twin: 0.42,
    twinInterval: 7,
  }),
  voice("earth-root", "Earth Root", {
    waveform: "triangle",
    filterType: "lowpass",
    cutoff: 980,
    resonance: 1.4,
    octave: -1,
    attack: 0.03,
    decay: 0.34,
    sustain: 0.92,
    release: 0.78,
    waters: 0.12,
    unison: 3,
    twin: 0.55,
    twinInterval: -12,
    volume: 0.9,
  }),
  voice("fire-bite", "Fire Bite", {
    waveform: "sawtooth",
    cutoff: 4200,
    resonance: 3.1,
    attack: 0.002,
    decay: 0.16,
    sustain: 0.58,
    release: 0.14,
    halloween: 0.32,
    unison: 1,
    twin: 0.38,
    twinInterval: 7,
    volume: 0.88,
  }),
  voice("water-room", "Water Room", {
    waveform: "sine",
    cutoff: 2400,
    resonance: 0.6,
    attack: 0.14,
    decay: 0.48,
    sustain: 0.9,
    release: 1.1,
    waters: 0.55,
    aether: 0.12,
    unison: 2,
    twin: 0.28,
    twinInterval: 12,
    volume: 0.88,
  }),
  voice("wind-cut", "Wind Cut", {
    waveform: "triangle",
    filterType: "highpass",
    cutoff: 380,
    resonance: 1.1,
    attack: 0.028,
    decay: 0.2,
    sustain: 0.7,
    release: 0.38,
    aether: 0.26,
    waters: 0.08,
    unison: 3,
    twin: 0.48,
    twinInterval: 19,
    volume: 0.86,
  }),
  voice("twin-fifth", "Twin Fifth", {
    waveform: "sawtooth",
    cutoff: 1800,
    resonance: 2.4,
    attack: 0.01,
    decay: 0.28,
    sustain: 0.72,
    release: 0.4,
    unison: 2,
    twin: 0.82,
    twinInterval: 7,
  }),
  voice("twin-octave", "Twin Octave", {
    waveform: "square",
    cutoff: 1100,
    resonance: 2.8,
    attack: 0.006,
    decay: 0.22,
    sustain: 0.6,
    release: 0.32,
    octave: -1,
    unison: 2,
    twin: 0.78,
    twinInterval: 12,
    halloween: 0.12,
  }),
  voice("aether-choir", "Aether Choir", {
    waveform: "triangle",
    cutoff: 1680,
    resonance: 0.85,
    attack: 0.55,
    decay: 0.9,
    sustain: 0.88,
    release: 2.1,
    unison: 3,
    aether: 0.42,
    waters: 0.18,
    twin: 0.35,
    twinInterval: 7,
  }),
  voice("gulf-night", "Gulf Night", {
    waveform: "sine",
    filterType: "lowpass",
    cutoff: 640,
    resonance: 1.6,
    attack: 0.28,
    decay: 0.7,
    sustain: 0.82,
    release: 1.6,
    waters: 0.42,
    aether: 0.1,
    unison: 2,
    twin: 0.22,
    twinInterval: 5,
  }),
  voice("thirty-three", "Thirty Three", {
    waveform: "pulse",
    pulseWidth: 0.18,
    cutoff: 1600,
    resonance: 3.4,
    attack: 0.006,
    decay: 0.22,
    sustain: 0.5,
    release: 0.33,
    unison: 2,
    halloween: 0.22,
    twin: 0.4,
    twinInterval: 3,
  }),
  voice("pearl-drift", "Pearl Drift", {
    waveform: "triangle",
    cutoff: 2400,
    resonance: 0.9,
    attack: 0.12,
    decay: 0.8,
    sustain: 0.78,
    release: 1.2,
    unison: 3,
    waters: 0.22,
    aether: 0.08,
  }),
  voice("hauntwater", "Hauntwater", {
    waveform: "sawtooth",
    cutoff: 880,
    resonance: 3.6,
    attack: 0.05,
    decay: 0.4,
    sustain: 0.58,
    release: 1.3,
    halloween: 0.36,
    waters: 0.32,
    unison: 2,
    twin: 0.3,
    twinInterval: 7,
  }),
  voice("cinder-coil", "Cinder Coil", {
    waveform: "sawtooth",
    cutoff: 2400,
    resonance: 4.2,
    attack: 0.002,
    decay: 0.18,
    sustain: 0.28,
    release: 0.12,
    halloween: 0.3,
    unison: 1,
    twin: 0.25,
    twinInterval: 7,
  }),
  voice("tide-wurm", "Tide Wurm", {
    waveform: "triangle",
    filterType: "bandpass",
    cutoff: 620,
    resonance: 2.8,
    attack: 0.2,
    decay: 0.5,
    sustain: 0.8,
    release: 1.1,
    waters: 0.48,
    unison: 2,
    octave: -1,
    twin: 0.33,
    twinInterval: 12,
  }),
  voice("skyride", "Skyride", {
    waveform: "triangle",
    filterType: "highpass",
    cutoff: 1400,
    resonance: 1.8,
    attack: 0.03,
    decay: 0.24,
    sustain: 0.6,
    release: 0.45,
    octave: 1,
    unison: 3,
    waters: 0.12,
    twin: 0.45,
    twinInterval: 7,
  }),
  voice("pale-current", "Pale Current", {
    waveform: "sine",
    cutoff: 1100,
    resonance: 2.2,
    attack: 0.4,
    decay: 0.9,
    sustain: 0.86,
    release: 2.2,
    waters: 0.45,
    aether: 0.16,
    unison: 2,
  }),
  voice("ember-keys", "Ember Keys", {
    waveform: "sine",
    cutoff: 3600,
    resonance: 1.1,
    attack: 0.004,
    decay: 0.38,
    sustain: 0.52,
    release: 0.4,
    halloween: 0.22,
    unison: 2,
    twin: 0.2,
    twinInterval: 12,
  }),
  voice("root-bass", "Root Bass", {
    waveform: "square",
    cutoff: 380,
    resonance: 4.6,
    attack: 0.002,
    decay: 0.2,
    sustain: 0.4,
    release: 0.14,
    octave: -1,
    unison: 2,
    twin: 0.62,
    twinInterval: 12,
  }),
  voice("gale-lead", "Gale Lead", {
    waveform: "sawtooth",
    filterType: "highpass",
    cutoff: 900,
    resonance: 3.2,
    attack: 0.01,
    decay: 0.16,
    sustain: 0.62,
    release: 0.22,
    octave: 1,
    unison: 3,
    twin: 0.5,
    twinInterval: 7,
  }),
  voice("night-pad", "Night Pad", {
    waveform: "sawtooth",
    cutoff: 820,
    resonance: 1.05,
    attack: 0.9,
    decay: 1.2,
    sustain: 0.84,
    release: 2.0,
    unison: 3,
    waters: 0.28,
    aether: 0.2,
    twin: 0.36,
    twinInterval: 5,
  }),
  voice("stone-pluck", "Stone Pluck", {
    waveform: "triangle",
    cutoff: 1600,
    resonance: 4.0,
    attack: 0.001,
    decay: 0.26,
    sustain: 0.05,
    release: 0.16,
    octave: -1,
    unison: 1,
  }),
  voice("whisper-saw", "Whisper Saw", {
    waveform: "sawtooth",
    cutoff: 540,
    resonance: 2.4,
    attack: 0.08,
    decay: 0.5,
    sustain: 0.66,
    release: 0.8,
    halloween: 0.36,
    unison: 2,
  }),
  voice("glass-water", "Glass Water", {
    waveform: "sine",
    filterType: "bandpass",
    cutoff: 920,
    resonance: 3.6,
    attack: 0.16,
    decay: 0.4,
    sustain: 0.7,
    release: 0.7,
    waters: 0.38,
    aether: 0.14,
    unison: 2,
  }),
  voice("dusk-octave", "Dusk Octave", {
    waveform: "triangle",
    cutoff: 1900,
    resonance: 1.4,
    attack: 0.06,
    decay: 0.35,
    sustain: 0.6,
    release: 0.55,
    octave: 1,
    unison: 2,
    halloween: 0.14,
    twin: 0.7,
    twinInterval: 12,
  }),
  voice("salt-air", "Salt Air", {
    waveform: "triangle",
    filterType: "highpass",
    cutoff: 2100,
    resonance: 1.2,
    attack: 0.07,
    decay: 0.3,
    sustain: 0.5,
    release: 0.6,
    waters: 0.38,
    unison: 3,
  }),
  voice("lindworm", "Lindworm", {
    waveform: "square",
    cutoff: 1100,
    resonance: 4.0,
    attack: 0.02,
    decay: 0.28,
    sustain: 0.48,
    release: 0.5,
    halloween: 0.28,
    unison: 2,
    twin: 0.44,
    twinInterval: 7,
  }),
  voice("black-gulf", "Black Gulf", {
    waveform: "sine",
    cutoff: 280,
    resonance: 1.8,
    attack: 0.35,
    decay: 0.8,
    sustain: 0.9,
    release: 2.4,
    octave: -1,
    waters: 0.5,
    aether: 0.18,
    unison: 2,
    twin: 0.4,
    twinInterval: -5,
  }),
  voice("high-forge", "High Forge", {
    waveform: "pulse",
    pulseWidth: 0.12,
    cutoff: 2800,
    resonance: 2.8,
    attack: 0.003,
    decay: 0.14,
    sustain: 0.45,
    release: 0.18,
    octave: 1,
    unison: 2,
  }),
  voice("low-ember", "Low Ember", {
    waveform: "sawtooth",
    cutoff: 460,
    resonance: 5.0,
    attack: 0.01,
    decay: 0.32,
    sustain: 0.55,
    release: 0.7,
    octave: -1,
    halloween: 0.32,
    unison: 2,
    twin: 0.35,
    twinInterval: 7,
  }),
  voice("choir-drift", "Choir Drift", {
    waveform: "triangle",
    cutoff: 1400,
    resonance: 0.7,
    attack: 0.7,
    decay: 1.0,
    sustain: 0.88,
    release: 1.8,
    unison: 3,
    waters: 0.2,
    aether: 0.28,
    twin: 0.3,
    twinInterval: 4,
  }),
  voice("pulse-haunt", "Pulse Haunt", {
    waveform: "pulse",
    pulseWidth: 0.32,
    cutoff: 1500,
    resonance: 4.0,
    attack: 0.004,
    decay: 0.2,
    sustain: 0.4,
    release: 0.8,
    halloween: 0.42,
    unison: 1,
    twin: 0.22,
    twinInterval: 7,
  }),
  voice("zephyr", "Zephyr", {
    waveform: "sine",
    filterType: "highpass",
    cutoff: 1200,
    resonance: 1.5,
    attack: 0.05,
    decay: 0.22,
    sustain: 0.58,
    release: 0.5,
    octave: 1,
    unison: 3,
    aether: 0.2,
  }),
  voice("marsh-sine", "Marsh Sine", {
    waveform: "sine",
    filterType: "lowpass",
    cutoff: 700,
    resonance: 2.0,
    attack: 0.18,
    decay: 0.55,
    sustain: 0.75,
    release: 1.0,
    waters: 0.5,
    unison: 2,
  }),
  voice("iron-pluck", "Iron Pluck", {
    waveform: "square",
    cutoff: 2400,
    resonance: 3.8,
    attack: 0.001,
    decay: 0.22,
    sustain: 0.08,
    release: 0.12,
    unison: 2,
  }),
  voice("crown-saw", "Crown Saw", {
    waveform: "sawtooth",
    cutoff: 2600,
    resonance: 2.6,
    attack: 0.008,
    decay: 0.18,
    sustain: 0.68,
    release: 0.28,
    unison: 3,
    octave: 0,
    twin: 0.6,
    twinInterval: 7,
  }),
  voice("still-waters", "Still Waters", {
    waveform: "triangle",
    cutoff: 900,
    resonance: 1.3,
    attack: 0.5,
    decay: 0.9,
    sustain: 0.92,
    release: 2.6,
    waters: 0.52,
    aether: 0.12,
    unison: 2,
  }),
  voice("open-sky", "Open Sky", {
    waveform: "triangle",
    filterType: "highpass",
    cutoff: 800,
    resonance: 0.9,
    attack: 0.1,
    decay: 0.4,
    sustain: 0.7,
    release: 0.9,
    octave: 1,
    unison: 3,
    waters: 0.08,
    twin: 0.4,
    twinInterval: 19,
  }),
  voice("hollow-square", "Hollow Square", {
    waveform: "square",
    cutoff: 1300,
    resonance: 2.2,
    attack: 0.02,
    decay: 0.3,
    sustain: 0.62,
    release: 0.4,
    unison: 2,
    halloween: 0.16,
  }),
  voice("last-light", "Last Light", {
    waveform: "sine",
    cutoff: 1600,
    resonance: 1.0,
    attack: 0.22,
    decay: 0.7,
    sustain: 0.65,
    release: 2.8,
    halloween: 0.28,
    waters: 0.34,
    aether: 0.22,
    unison: 2,
    twin: 0.25,
    twinInterval: 7,
  }),
];
